// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	class "alta-dashboard-be/features/class"

	mock "github.com/stretchr/testify/mock"
)

// ClassData_ is an autogenerated mock type for the ClassData_ type
type ClassData_ struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ClassData_) Create(_a0 class.ClassCore) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(class.ClassCore) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *ClassData_) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit
func (_m *ClassData_) GetAll(page int, limit int) ([]class.ClassCore, error) {
	ret := _m.Called(page, limit)

	var r0 []class.ClassCore
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]class.ClassCore, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []class.ClassCore); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]class.ClassCore)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *ClassData_) GetOne(id int) (class.ClassCore, error) {
	ret := _m.Called(id)

	var r0 class.ClassCore
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (class.ClassCore, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) class.ClassCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(class.ClassCore)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, _a1
func (_m *ClassData_) Update(id int, _a1 class.ClassCore) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, class.ClassCore) error); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClassData_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewClassData_ creates a new instance of ClassData_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClassData_(t mockConstructorTestingTNewClassData_) *ClassData_ {
	mock := &ClassData_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
