// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	class "alta-dashboard-be/features/class"

	mock "github.com/stretchr/testify/mock"
)

// ClassService_ is an autogenerated mock type for the ClassService_ type
type ClassService_ struct {
	mock.Mock
}

// Create provides a mock function with given fields: userID, _a1
func (_m *ClassService_) Create(userID int, _a1 class.ClassCore) error {
	ret := _m.Called(userID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, class.ClassCore) error); ok {
		r0 = rf(userID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: userID, id
func (_m *ClassService_) Delete(userID int, id int) error {
	ret := _m.Called(userID, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit
func (_m *ClassService_) GetAll(page int, limit int) ([]class.ClassCore, error) {
	ret := _m.Called(page, limit)

	var r0 []class.ClassCore
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]class.ClassCore, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []class.ClassCore); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]class.ClassCore)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *ClassService_) GetOne(id int) (class.ClassCore, error) {
	ret := _m.Called(id)

	var r0 class.ClassCore
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (class.ClassCore, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) class.ClassCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(class.ClassCore)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userID, id, _a2
func (_m *ClassService_) Update(userID int, id int, _a2 class.ClassCore) error {
	ret := _m.Called(userID, id, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, class.ClassCore) error); ok {
		r0 = rf(userID, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClassService_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewClassService_ creates a new instance of ClassService_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClassService_(t mockConstructorTestingTNewClassService_) *ClassService_ {
	mock := &ClassService_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
