// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// LogDeliver_ is an autogenerated mock type for the LogDeliveryInterface_ type
type LogDeliver_ struct {
	mock.Mock
}

// AddLog provides a mock function with given fields: c
func (_m *LogDeliver_) AddLog(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLogDataByMenteeId provides a mock function with given fields: c
func (_m *LogDeliver_) GetLogDataByMenteeId(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLogDeliver_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogDeliver_ creates a new instance of LogDeliver_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogDeliver_(t mockConstructorTestingTNewLogDeliver_) *LogDeliver_ {
	mock := &LogDeliver_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
